export const caseStudies = [
  {
    slug: "nova-sports-live",
    name: "NOVA Sports Live",
    category: "SPORTS INFORMATION PLATFORM",
    image: "/novasportslive.png",
    url: "https://novasportslive.com",
    projectSlug: "nova-sports-live",
    summary: "A regional sports platform that brings local scores, teams, rankings and coverage together.",
    challenge: "Families, athletes and fans need an easier way to follow Northern Virginia high school sports across a season.",
    approach: "The platform organizes the scores, teams, rankings and coverage local sports audiences seek in a dedicated destination.",
    features: ["Sports scores and schedules", "Team and season information", "Regional rankings and coverage"],
    technology: "Responsive sports information website presenting schedules, scores, team information, rankings and coverage.",
    outcome: "A dedicated public place to explore scores, teams, rankings and regional coverage.",
  },
  {
    slug: "dmv-attack",
    name: "DMV Attack",
    category: "WEBSITE + ORGANIZATION TOOLS",
    image: "/dmvattack.jpeg",
    url: "https://dmvattack.com",
    projectSlug: "dmv-attack",
    summary: "A football organization website paired with practical tools for tryouts and coach administration.",
    challenge: "The program needs a public digital home that serves families and supports the staff running tryouts and teams.",
    approach: "The website brings public program information together with registration and coach administration tools.",
    features: ["Program and team information", "Tryout registration", "Coach administration tools"],
    technology: "Responsive organizational website with tryout registration and coach administration workflows.",
    outcome: "Families can find program information and tryout registration; coaches have organization tools.",
  },
  {
    slug: "coach-tae-qb",
    name: "Coach Tae QB",
    category: "ATHLETE DEVELOPMENT",
    image: "/CoachTaeqb.png",
    url: "https://coachtaeqb.com",
    projectSlug: "coach-tae-qb",
    summary: "A focused digital home for quarterback coaching, training programs and family inquiries.",
    challenge: "Athletes and parents need clear information about quarterback training and how to inquire.",
    approach: "The branded website presents training programs and provides a direct inquiry path.",
    features: ["Quarterback training information", "Program presentation", "Parent and athlete inquiries"],
    technology: "Responsive public website with program information and parent inquiry paths.",
    outcome: "A focused introduction to the quarterback training program and a direct contact path.",
  },
];
